version: "3"

services:
  medmorph_ehr:
    image: medmorph_fhir_cibmtr
    container_name: medmorph_ehr_cibmtr
    restart: on-failure
    ports:
      - "9180:8080"
    environment:
      - SERVER_ADDRESS=http://pathways.mitre.org:9180/fhir/
      - AUTH_SERVER_ADDRESS=http://moonshot-dev.mitre.org:8090/auth/realms/ehr/protocol/openid-connect/
      - SERVER_TITLE=MedMorph EHR CIBMTR
      - ADMIN_TOKEN=admin
      - REQUIRE_AUTH=true
      - CIBMTR_URL=http://pathways.mitre.org:4444/