version: "3"

services:
  medmorph_ehr:
    image: medmorph_fhir
    container_name: medmorph_ehr
    restart: on-failure
    ports:
      - "8180:8080"
    environment:
      - SERVER_ADDRESS=http://${LOCAL_IP}:8180/fhir/
      - AUTH_SERVER_ADDRESS=http://moonshot-dev.mitre.org:8090/auth/realms/ehr/protocol/openid-connect/
      - SERVER_TITLE=MedMorph EHR
      - ADMIN_TOKEN=admin
  knowledge_artifact:
    image: medmorph_fhir
    container_name: knowledge_artifact
    restart: on-failure
    ports:
      - "8190:8080"
    environment:
      - SERVER_ADDRESS=http://${LOCAL_IP}:8190/fhir/
      - AUTH_SERVER_ADDRESS=http://moonshot-dev.mitre.org:8090/auth/realms/knowledgeartifact/protocol/openid-connect/
      - SERVER_TITLE=Knowledge Artifact Repository
      - ADMIN_TOKEN=admin
  public_health_authority:
    image: medmorph_fhir
    container_name: public_health_authority
    restart: on-failure
    ports:
      - "8181:8080"
    environment:
      - SERVER_ADDRESS=http://${LOCAL_IP}:8181/fhir/
      - AUTH_SERVER_ADDRESS=http://moonshot-dev.mitre.org:8090/auth/realms/pha/protocol/openid-connect/
      - SERVER_TITLE=Public Health Authority
      - ADMIN_TOKEN=admin
