version: "3"

services:
  medmorph_ehr:
    image: medmorph_fhir
    container_name: medmorph_ehr
    restart: unless-stopped
    ports:
      - "8180:8080"
    environment:
      - SERVER_ADDRESS=http://pathways.mitre.org:8180/fhir/
      - AUTH_SERVER_ADDRESS=http://moonshot-dev.mitre.org:8090/auth/realms/ehr/protocol/openid-connect/
      - SERVER_TITLE=MedMorph EHR
      - ADMIN_TOKEN=admin
      - REQUIRE_AUTH=true
  knowledge_artifact:
    image: medmorph_fhir
    container_name: knowledge_artifact
    restart: unless-stopped
    ports:
      - "8190:8080"
    environment:
      - SERVER_ADDRESS=https://pathways.mitre.org:8550/fhir/
      - AUTH_SERVER_ADDRESS=http://moonshot-dev.mitre.org:8090/auth/realms/knowledgeartifact/protocol/openid-connect/
      - SERVER_TITLE=Knowledge Artifact Repository
      - ADMIN_TOKEN=admin
      - REQUIRE_AUTH=true
  public_health_authority:
    image: medmorph_fhir
    container_name: public_health_authority
    restart: unless-stopped
    ports:
      - "8181:8080"
    environment:
      - SERVER_ADDRESS=https://pathways.mitre.org:8660/fhir/
      - AUTH_SERVER_ADDRESS=http://moonshot-dev.mitre.org:8090/auth/realms/pha/protocol/openid-connect/
      - SERVER_TITLE=Public Health Authority
      - ADMIN_TOKEN=admin
      - REQUIRE_AUTH=true
