/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.mitre.hapifhir;

import org.junit.Test;

import ca.uhn.fhir.context.FhirContext;

import static org.junit.Assert.*;

import org.hl7.fhir.r4.model.Bundle;

public class ProcessMessageProviderTest {
    @Test public void testSomeLibraryMethod() {
    	FhirContext r4 = FhirContext.forR4();
    	
        ProcessMessageProvider classUnderTest = new ProcessMessageProvider(r4, (_a, _b) -> new Bundle());
        classUnderTest.processMessage(null, null, null, null);
        assertTrue("someLibraryMethod should return 'true'", true);
    }
}
